[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wirepy"
version = "0.2.4"
description = "WirePy is built on top of FastAPI with the core goal of maintaining large Python backends developed by multiple team members using a standardized project structure. It comes with built-in database connectivity and integrated Alembic migrations. Core components such as models, controllers, services, and schemas are already organized and ready to use. Instead of spending time setting up the project structure, you can simply install it via `pip` and start coding right away."
authors = [{ name = "Pradipta Bhuin", email = "bhuinjohn@gmail.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "pymysql",
    "python-dotenv",
    "alembic",
    "click",
    "pydantic[email]"
]

[project.scripts]
wirepy = "wirepy.cli:cli"

# ─────────────────────────────────────────────
# Tell setuptools EXACTLY which package to ship
# ─────────────────────────────────────────────
[tool.setuptools]
packages = ["wirepy", "wirepy.templates", "wirepy.templates.app", "wirepy.templates.app.core", "wirepy.templates.app.controllers","wirepy.templates.app.models", "wirepy.templates.app.routes", "wirepy.templates.app.schemas", "wirepy.templates.app.services", "wirepy.templates.app.database"]
include-package-data = true   #  so templates get bundled too








